Fix ##sequence-region metadata when tidying GFF3
Ensembl/ensembl-production pull request #535
Opened 2020-12-17 14:52 UTC by james-monkeyshines

## Description
Fix ##sequence-region metadata when tidying GFF3 (AFAIK, this only matters for human chrY, in which a gene is annotated partly in a PAR).

## Benefits
GFF3 dumps for human chrY are valid.

## Possible Drawbacks
Tidying is potentially slower - but wasn't noticeably so when tested.

2020-12-18 08:19 UTC, marcoooo approved these changes

2020-12-18 08:21 UTC, marcoooo requested changes
Some build failures can be fix easily
not ok 320 - /home/travis/build/Ensembl/ensembl-production/modules/t/../../modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/IndexWig.pm does not have an Apache v2.0 licence declaration and correct Copyright year [2016-2020] in the first 30 lines
not ok 321 - /home/travis/build/Ensembl/ensembl-production/modules/t/../../modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/CoordinateConverter.pm does not have an Apache v2.0 licence declaration and correct Copyright year [2016-2020] in the first 30 lines
not ok 322 - /home/travis/build/Ensembl/ensembl-production/modules/t/../../modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/Genome.pm does not have an Apache v2.0 licence declaration and correct Copyright year [2016-2020] in the first 30 lines
...

2020-12-18 09:59 UTC, james-monkeyshines commented
Fixes for the missing licence failures are on release/104, I've created another PR to merge them to master: #536

2020-12-21 21:23 UTC, marcoooo approved these changes

2020-12-21 21:24 UTC, merged