Codon migrations
Ensembl/ensembl-production pull request #572
Opened 2021-06-08 14:32 UTC by vinay-ebi

Modified pipeline conf file according to new codon server

2021-06-08 14:33 UTC, marcoooo approved these changes

2021-06-08 14:54 UTC, james-monkeyshines requested changes

2021-06-08 14:54 UTC, james-monkeyshines commented on modules/Bio/EnsEMBL/Production/Pipeline/OntologiesLoad/MartLoad.pm
> +    my $TMP_SQL = "/hps/scratch/mart.sql";
TSC say we need to have user names in the path. You can get that in Perl with `$ENV{'USER'}`. However, you then need to create the sub-directory, so it gets a little more complicated... Could either 1) build and create the path in the conf file and pass a parameter in here; or, 2) do something like we do with File::Path and File::Temp in https://github.com/Ensembl/ensembl-production/blob/release/105/modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScan.pm. (Or, these days, Path::Tiny is my go-to library for filesystem stuff, it has nice wrappers around that functionality.) Note that the latter option gives us an easy way to remove the file when the module exits.

2021-06-09 08:47 UTC, james-monkeyshines approved these changes

2021-06-09 09:50 UTC, merged