integrate homology dump steps into rr ftp pipeline
Ensembl/ensembl-production pull request #774
Opened 2023-02-28 10:14 UTC by vinay-ebi

## Description

Integrate Homology dump steps into RR ftp dump pipeline

## Benefits

Can run homoly dumps alone for any given division or species

2023-02-28 12:58 UTC, vinay-ebi commented
we can ignore the build failure related to licences those will be fixed during 110 merge to main 
Failed test '/home/travis/build/Ensembl/ensembl-production/modules/t/../../scripts/misc/tmux_ls.sh does not have an Apache v2.0 licence declaration and correct Copyright year [2016-2023] in the first 30 lines'

2023-03-02 15:28 UTC, marcoooo requested changes

2023-03-02 15:28 UTC, marcoooo commented on modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
> +	homology_dump_server_url => $self->get_server_url('st5'),
Just realised one thing, this pipeline won't work if the user doesn't have the shortcut setup in his environment, which is possible. Can't we just add the output of `$host_name details url` to the parameters? Simpler and more portable.

2023-03-02 16:47 UTC, vinay-ebi commented on modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
> +	homology_dump_server_url => $self->get_server_url('st5'),
yes we getting host details  : https://github.com/Ensembl/ensembl-production/pull/774/files#diff-7ee5c751c6f2c94fa9cc6306fe88fbd157487ccf192796e623bef1f898eb7659R86

2023-03-02 19:02 UTC, marcoooo requested changes

2023-03-02 19:02 UTC, marcoooo commented on modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
> +	homology_dump_server_url => $self->get_server_url('st5'),
No, I meant, do not use this `within` the pipeline, but put the string as a parameter to the pipeline. Something like "compara_host"

2023-03-03 14:02 UTC, marcoooo approved these changes

2023-03-03 14:10 UTC, merged