Added a failure if gzip fails to complete properly
Ensembl/ensembl-production pull request #804
Opened 2023-06-08 16:54 UTC by dpopleton

**Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion**

## Requirements

- Filling out the template is required. 
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#updating-the-schema)
    - the PR must not fail unit testing

## Description

_Using one or more sentences, describe in detail the proposed changes._

## Use case

_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._

## Benefits

_If applicable, describe the advantages the changes will have._

## Possible Drawbacks

_If applicable, describe any possible undesirable consequence of the changes._

## Testing

- [ ] Have you added/modified unit tests to test the changes?
- [ ] If so, do the tests pass?
- [ ] Have you run the entire test suite and no regression was detected?
- [ ] TravisCI passed on your branch

Dependencies
------------

> If applicable, define what code dependencies were added and/or updated.

2023-06-12 07:01 UTC, marcoooo commented on modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileXref.pm
> +  if ($xrefs_exist != 1) {
Not sure about this one, can you explain, please?

2023-06-12 07:02 UTC, marcoooo commented
Can you update the description to give a context to this PR please? Why is it so different from the one against 111?

2023-06-12 10:14 UTC, marcoooo approved these changes

2023-06-12 10:15 UTC, marcoooo requested changes
Please fill in the description

2023-06-13 08:14 UTC, vinay-ebi commented on modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/DumpFile.pm
> +              { "compress" => [@compress] }, 1);
```suggestion
              { "compress" => \@compress }, 1);
```

2023-06-13 11:57 UTC, vinay-ebi approved these changes

2023-06-13 14:12 UTC, marcoooo approved these changes

2023-06-13 14:14 UTC, merged